#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000M
#SBATCH --time=03:00:00
#SBATCH --job-name=index



#index to the reference
module add UHTS/Aligner/hisat/2.2.1

hisat2-build /data/courses/rnaseq/toxoplasma_de/stille_workspace/hisat/*.fastq.gz /data/courses/rnaseq/toxoplasma_de/genome/Mus_musculus.GRCm39.dna.primary_assembly.fa

#------------------------------------------------------------------------------------------------------------------------------

#!/bin/bash
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8000M
#SBATCH --time=02:00:00
#SBATCH --job-name=map



module add UHTS/Aligner/hisat/2.2.1

hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821918_1.fastq -2 SRR7821918_2.fastq -S SRR7821918.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821919_1.fastq -2 SRR7821919_2.fastq -S SRR7821919.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821920_1.fastq -2 SRR7821920_2.fastq -S SRR7821920.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821921_1.fastq -2 SRR7821921_2.fastq -S SRR7821921.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821922_1.fastq -2 SRR7821922_2.fastq -S SRR7821922.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821937_1.fastq -2 SRR7821937_2.fastq -S SRR7821937.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821938_1.fastq -2 SRR7821938_2.fastq -S SRR7821938.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821939_1.fastq -2 SRR7821939_2.fastq -S SRR7821939.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821949_1.fastq -2 SRR7821949_2.fastq -S SRR7821949.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821950_1.fastq -2 SRR7821950_2.fastq -S SRR7821950.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821951_1.fastq -2 SRR7821951_2.fastq -S SRR7821951.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821952_1.fastq -2 SRR7821952_2.fastq -S SRR7821952.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821953_1.fastq -2 SRR7821953_2.fastq -S SRR7821953.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821968_1.fastq -2 SRR7821968_2.fastq -S SRR7821968.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821969_1.fastq -2 SRR7821969_2.fastq -S SRR7821969.sam
hisat2 -q -x Mus_musculus.GRCm39 -1 SRR7821970_1.fastq -2 SRR7821970_2.fastq -S SRR7821970.sam


#---------------------------------------------------------------------------------------------------------

#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000M
#SBATCH --time=03:00:00
#SBATCH --job-name=samview


module add UHTS/Analysis/samtools/1.10

samtools view -bS SRR7821919.sam > SRR7821919.bam
samtools view -bS SRR7821920.sam > SRR7821920.bam
samtools view -bS SRR7821921.sam > SRR7821921.bam
samtools view -bS SRR7821922.sam > SRR7821922.bam
samtools view -bS SRR7821937.sam > SRR7821937.bam
samtools view -bS SRR7821938.sam > SRR7821938.bam
samtools view -bS SRR7821939.sam > SRR7821939.bam
samtools view -bS SRR7821949.sam > SRR7821949.bam
samtools view -bS SRR7821950.sam > SRR7821950.bam
samtools view -bS SRR7821951.sam > SRR7821951.bam
samtools view -bS SRR7821952.sam > SRR7821952.bam
samtools view -bS SRR7821953.sam > SRR7821953.bam
samtools view -bS SRR7821968.sam > SRR7821968.bam
samtools view -bS SRR7821969.sam > SRR7821969.bam
samtools view -bS SRR7821970.sam > SRR7821970.bam

#-----------------------------------------------------------------------------------------------------------------


#!/bin/bash
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=25000M
#SBATCH --time=08:00:00
#SBATCH --job-name=samsort



module add UHTS/Analysis/samtools/1.10


samtools sort SRR7821918.sam -o SRR7821918_sorted.bam
samtools sort SRR7821919.sam -o SRR7821919_sorted.bam
samtools sort SRR7821920.sam -o SRR7821920_sorted.bam
samtools sort SRR7821921.sam -o SRR7821921_sorted.bam
samtools sort SRR7821922.sam -o SRR7821922_sorted.bam
samtools sort SRR7821937.sam -o SRR7821937_sorted.bam
samtools sort SRR7821938.sam -o SRR7821938_sorted.bam
samtools sort SRR7821939.sam -o SRR7821939_sorted.bam
samtools sort SRR7821949.sam -o SRR7821949_sorted.bam
samtools sort SRR7821950.sam -o SRR7821950_sorted.bam
samtools sort SRR7821951.sam -o SRR7821951_sorted.bam
samtools sort SRR7821952.sam -o SRR7821952_sorted.bam
samtools sort SRR7821953.sam -o SRR7821953_sorted.bam
samtools sort SRR7821968.sam -o SRR7821968_sorted.bam
samtools sort SRR7821969.sam -o SRR7821969_sorted.bam
samtools sort SRR7821970.sam -o SRR7821970_sorted.bam


#---------------------------------------------------------------------------------------------------------------



#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000M
#SBATCH --time=03:00:00
#SBATCH --job-name=index_sorted_bam




module add UHTS/Analysis/samtools/1.10


samtools index SRR7821918_sorted.bam
samtools index SRR7821919_sorted.bam
samtools index SRR7821920_sorted.bam
samtools index SRR7821921_sorted.bam
samtools index SRR7821922_sorted.bam
samtools index SRR7821937_sorted.bam
samtools index SRR7821938_sorted.bam
samtools index SRR7821939_sorted.bam
samtools index SRR7821949_sorted.bam
samtools index SRR7821950_sorted.bam
samtools index SRR7821951_sorted.bam
samtools index SRR7821952_sorted.bam
samtools index SRR7821953_sorted.bam
samtools index SRR7821968_sorted.bam
samtools index SRR7821969_sorted.bam
samtools index SRR7821970_sorted.bam





