#!/bin/bash
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8000M
#SBATCH --time=03:00:00
#SBATCH --job-name=featurecounts



module add UHTS/Analysis/subread/2.0.1

featureCounts -p -s 2 -a Mus_musculus.GRCm39.104.gtf -o Count.txt *_sorted.bam

